coverage:
  paths:
    - coverage/.resultset.json
  acceptable: 60%
codeToTestRatio:
  acceptable: 1:2
  code:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
  test:
    - 'spec/**/*_spec.rb'
testExecutionTime:
  acceptable: 0.1sec
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
  hideFooterLink: false
  deletePrevious: true
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
