AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 3.1.2

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Style/HashSyntax:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*'

Metrics/MethodLength:
  Max: 50
