openapi: 3.0.0

info:
  title: Post API
  version: 0.0.0
  description: test
  contact:
    name: test
    url: https://example.com/

paths:
  /posts/{id}:
    get:
      summary: "Get API"
      operationId: getPost
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: "integer"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: "object"
                additionalProperties: false
                required:
                  - id
                properties:
                  id:
                    type: "integer"
                    format: "int64"
                  title:
                    type: "string"
                    example: "title"
                  body:
                    type: "string"
                    example: "body"
