name: Setup Rails application

on:
  workflow_call:

inputs:
  ruby-version:
    default: '3.1.2'
    required: false
  freetds-version:
    default: '1.3.17'
    required: false

runs:
  using: "composite"
  steps:
    - name: Cache freetds
      id: cache-Primes
      uses: actions/cache@v4
      with:
        path: ~/freetds-${{ inputs.freetds-version }}
        key: ${{ runner.os }}-freetds
    - name: Cache node modules
      uses: actions/cache@v4
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install freetds
      env:
        FREETDS_VERSION: ${{ inputs.freetds-version }}
      shell: bash
      run: |
        cd ~/
        if [ ! -d "freetds-${FREETDS_VERSION}" ]; then
          sudo apt-get update --allow-releaseinfo-change
          sudo apt-get -y install libsasl2-dev
          wget http://www.freetds.org/files/stable/freetds-${FREETDS_VERSION}.tar.gz
          tar -xzf freetds-${FREETDS_VERSION}.tar.gz
          cd freetds-${FREETDS_VERSION}
          sudo ./configure --with-tdsver=7.4
          sudo make
          cd ..
        fi
        cd freetds-${FREETDS_VERSION}
        sudo make install
    - name: Install mecab
      shell: bash
      run: |
        sudo apt-get update --allow-releaseinfo-change
        sudo apt-get install -y mecab libmecab-dev mecab-ipadic mecab-ipadic-utf8
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: true
    - name: List the state of node modules
      if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      continue-on-error: true
      shell: bash
      run: npm list
    - name: Install dependencies
      shell: bash
      run: npm install
