name: Setup Rails application

on:
  workflow_call:

inputs:
  freetds-version:
    default: "1.3.17"
    required: false

runs:
  using: "composite"
  steps:
    - name: Cache freetds
      uses: actions/cache@v4
      with:
        path: ${{ runner.temp }}/freetds-${{ inputs.freetds-version }}
        key: ${{ runner.os }}-freetds-${{ inputs.freetds-version }}
    - name: Install packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: curl wget build-essential awscli git mecab libmecab-dev mecab-ipadic mecab-ipadic-utf8 libjemalloc2 pkg-config freetds-dev libxml2-utils
        version: 1.0
    - name: Install freetds
      env:
        FREETDS_VERSION: ${{ inputs.freetds-version }}
      shell: bash
      working-directory: ${{ runner.temp }}
      run: |
        if [ ! -d "freetds-${FREETDS_VERSION}" ]; then
          wget http://www.freetds.org/files/stable/freetds-${FREETDS_VERSION}.tar.gz
          tar -xzf freetds-${FREETDS_VERSION}.tar.gz
          cd freetds-${FREETDS_VERSION}
          sudo ./configure --prefix=/usr/local --with-tdsver=7.4
          sudo make
          cd ..
        fi
        cd freetds-${FREETDS_VERSION}
        sudo make install
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
    - name: Install dpendencies
      shell: bash
      run: npm ci
