name: Build elasticsearch

on:
  workflow_call:
    outputs:
      image:
        value: ${{ jobs.build.outputs.image }}
      username:
        value: AWS
      password:
        value: ${{ jobs.build.outputs.password }}
  workflow_dispatch:

env:
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_ARN: ${{ vars.OIDC_ROLE_ARN_STG }}
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: |
            containers/elasticsearch
      - name: Underscore AWS_REGION value
        id: aws-region-underscore
        run: |
          echo "value=${AWS_REGION//-/_}" >> "$GITHUB_OUTPUT"
      - uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        with:
          mask-password: 'false'
      - uses: theowenyoung/folder-hash@aa67b99197f85ada57370fc803e6a39e5fe529d0 # v3
        id: elasticsearch-container
        with:
          path: |
            containers/elasticsearch
      - uses: tyriis/docker-image-tag-exists@d0550080f1fad88ce68d5da17bded7aa69f9a5c8 # v2.0.0
        id: docker-image-tag-exists
        with:
          registry: ${{ steps.login-ecr.outputs.registry }}
          repository: ${{ env.ECR_REPOSITORY }}
          tag: ${{ steps.elasticsearch-container.outputs.hash }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
        if: steps.docker-image-tag-exists.outputs.tag == 'not found'
      - name: Login to Docker Hub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        if: steps.docker-image-tag-exists.outputs.tag == 'not found'
        with:
          registry: ${{ steps.login-ecr.outputs.registry }}
      - name: Build and push API
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
        if: steps.docker-image-tag-exists.outputs.tag == 'not found'
        with:
          push: true
          provenance: false
          context: containers/elasticsearch
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.elasticsearch-container.outputs.hash }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
    outputs:
      image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.elasticsearch-container.outputs.hash }}
      password: ${{ steps.login-ecr.outputs[format('docker_password_{0}_dkr_ecr_{1}_amazonaws_com', env.AWS_ACCOUNT_ID, steps.aws-region-underscore.outputs.value)] }}
