name: Check

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  check-fixup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check
        id: check_fixup
        run: |
          git fetch origin ${{ github.base_ref }}

          if git log --oneline origin/${{ github.base_ref }}..HEAD | grep -qE "^.*fixup!"; then
            echo "has_fixup=true" >> $GITHUB_OUTPUT
          else
            echo "has_fixup=false" >> $GITHUB_OUTPUT
          fi
