name: Redis container example
on: push

env:
  RUBY_VERSION: 3.1.2
  FREETDS_VERSION: 1.3.17

jobs:
  build:
    runs-on: ubuntu-22.04
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2017-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Cache freetds
        id: cache-Primes
        uses: actions/cache@v4
        with:
          path: freetds-${{ env.FREETDS_VERSION }}
          key: ${{ runner.os }}-freetds
      - name: Install freetds
        run: |
          if [ ! -d "freetds-${FREETDS_VERSION}" ]; then
            sudo apt-get update
            sudo apt-get -y install wget build-essential libc6-dev
            sudo wget http://www.freetds.org/files/stable/freetds-${FREETDS_VERSION}.tar.gz
            sudo tar -xzf freetds-${FREETDS_VERSION}.tar.gz
            cd freetds-${FREETDS_VERSION}
            sudo ./configure --prefix=/usr/local --with-tdsver=7.3
            sudo make
            cd ..
          fi
          cd freetds-${FREETDS_VERSION}
          sudo make install
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: bundle exec rubocop
        run: bundle exec rubocop
