name: Report coverage

on:
  pull_request:
    types: opened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TEST_WORKFLOW_FILE_NAME: test.yml
  COVERAGE_ARTIFACT_NAME: coverage

defaults:
  run:
    shell: bash

jobs:
  report-coverage:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
      actions: read
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get run_id of test workflow
        id: get-run-id
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${GITHUB_REPOSITORY}/actions/workflows/${TEST_WORKFLOW_FILE_NAME}/runs?head_sha=${{ github.event.pull_request.head.sha }}&status=completed" | \
            jq '.workflow_runs | sort_by(.id)[] | select(.conclusion == "success" or .conclusion == "failure") | .id' | \
            jq -sr '"test-run-id=\(last)"' >> $GITHUB_OUTPUT
      - name: Download coverage
        uses: dawidd6/action-download-artifact@v6
        id: download-coverage
        if: ${{ steps.get-run-id.outputs.test-run-id != 'null' }}
        with:
          name: coverage
          path: coverage
          run_id: ${{ steps.get-run-id.outputs.test-run-id }}
      - name: Coverage Report by octocov
        if: ${{ steps.download-coverage.outputs.found_artifact }}
        uses: k1LoW/octocov-action@v1
