name: Reviewdog

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUNDLE_ENTERPRISE__CONTRIBSYS__COM: ${{ secrets.BUNDLE_ENTERPRISE__CONTRIBSYS__COM }}

defaults:
  run:
    shell: bash

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        name: Checkout "${{ github.base_ref }}"
        with:
          ref: ${{ github.base_ref }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup-rails-application
      - uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
      - uses: reviewdog/action-rubocop@fcb74ba274da10b18d038d0bcddaae3518739634 # v2.21.2
        with:
          reporter: github-pr-review
          skip_install: true
          use_bundler: true
          only_changed: true
          filter_mode: nofilter
          rubocop_flags: '--fail-level convention'
      - uses: reviewdog/action-eslint@2fee6dd72a5419ff4113f694e2068d2a03bb35dd # v1.33.2
        if: success() || failure()
        with:
          github_token: ${{ github.token }}
          reporter: github-pr-review
          eslint_flags: $(git diff --name-only --diff-filter=ACMR origin/${{ github.base_ref }} -- 'app/**/*.js')
          reviewdog_flags: -diff="git diff origin/${{ github.base_ref }} app/**/*.js"
          fail_on_error: true
      - name: Filter changed scss
        id: filter-changed-scss
        if: success() || failure()
        run: |
          files=$(git diff --name-only --diff-filter=ACMR origin/${{ github.base_ref }} -- 'app/**/*.scss' | tr '\n' ' ')
          echo "files=${files}" >> $GITHUB_OUTPUT
      - uses: reviewdog/action-stylelint@dd2b435cc6a7c82705307a9dee740c9bbaa10411 # v1.30.2
        if: (success() || failure()) && steps.filter-changed-scss.outputs.files != ''
        with:
          github_token: ${{ github.token }}
          reporter: github-pr-review
          stylelint_input: $(git diff --name-only --diff-filter=ACMR origin/${{ github.base_ref }} -- 'app/**/*.scss')
          fail_on_error: true
      - name: Run slim-lint with reviewdog
        if: ${{ (success() || failure()) }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          bundle exec slim-lint --reporter json $(git diff --name-only --diff-filter=ACMR origin/${{ github.base_ref }} -- 'app/views/**/*.slim') | \
            jq '.files[]' | jq -c '. as $files | .offenses[] | {message: .message, location: {path: $files.path, range: {start: {line: .location.line}}}, severity: .severity}' | \
            reviewdog -f=rdjsonl -name=slim-lint -reporter=github-pr-review -level warning -filter-mode=nofilter
