name: Reviewdog

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUNDLE_ENTERPRISE__CONTRIBSYS__COM: ${{ secrets.BUNDLE_ENTERPRISE__CONTRIBSYS__COM }}

defaults:
  run:
    shell: bash

jobs:
  reviewdog:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout "${{ github.base_ref }}"
        with:
          ref: ${{ github.base_ref }}
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-rails-application
      - uses: reviewdog/action-setup@v1
      - uses: reviewdog/action-rubocop@v2
        with:
          reporter: github-pr-review
          skip_install: true
          use_bundler: true
          fail_on_error: true
      - uses: reviewdog/action-eslint@v1
        if: success() || failure()
        with:
          github_token: ${{ github.token }}
          reporter: github-pr-review
          eslint_flags: $(git diff --name-only --diff-filter=ACMR origin/${{ github.base_ref }} -- 'app/**/*.js')
          reviewdog_flags: -diff="git diff origin/${{ github.base_ref }} app/**/*.js"
          fail_on_error: true
      - name: Filter changed scss
        id: filter-changed-scss
        if: success() || failure()
        run: |
          files=$(git diff --name-only --diff-filter=ACMR origin/${{ github.base_ref }} -- 'app/**/*.scss' | tr '\n' ' ')
          echo "files=${files}" >> $GITHUB_OUTPUT
      - uses: reviewdog/action-stylelint@v1
        if: (success() || failure()) && steps.filter-changed-scss.outputs.files != ''
        with:
          github_token: ${{ github.token }}
          reporter: github-pr-review
          stylelint_input: $(git diff --name-only --diff-filter=ACMR origin/${{ github.base_ref }} -- 'app/**/*.scss')
          fail_on_error: true
      - name: Run slim-lint with reviewdog
        if: ${{ (success() || failure()) }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          bundle exec slim-lint --reporter json app/views | \
            jq '.files[]' | jq -c '. as $input | .offenses[] | {message: .message, location: {path: $input.path, range: {start: {line: .location.line}}}}' | \
            reviewdog -f=rdjsonl -name="slim-lint" -reporter=github-pr-review -level warning
