name: Reviewdog
on:
  push:

env:
  RUBY_VERSION: 3.1.2

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
      - name: Install dependencies
        run: npm install
      - uses: reviewdog/action-rubocop@v2
        with:
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'github-check' }}
          skip_install: true
          use_bundler: true
          fail_on_error: true
      - uses: reviewdog/action-eslint@v1
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'github-check' }}
            eslint_flags: app/**/*.js
            # reviewdog_flags: -diff="git diff origin/main app/**/*.js"
          fail_on_error: true
      - uses: reviewdog/action-stylelint@v1
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'github-check' }}
          stylelint_input: app/**/*.scss
          fail_on_error: true
