name: Reviewdog

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUNDLE_ENTERPRISE__CONTRIBSYS__COM: ${{ secrets.BUNDLE_ENTERPRISE__CONTRIBSYS__COM }}

jobs:
  reviewdog:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - run: echo "FETCH_DEPTH=$(( commits + 1 ))" >> $GITHUB_ENV
        env:
          commits: ${{ github.event.pull_request.commits }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}
      - uses: ./.github/actions/setup-rails-application
      - uses: reviewdog/action-rubocop@v2
        with:
          reporter: github-pr-review
          skip_install: true
          use_bundler: true
          fail_on_error: true
      - uses: reviewdog/action-eslint@v1
        if: success() || failure()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: $(git diff --name-only --diff-filter=ACMR origin/${{ github.event.repository.default_branch }} -- 'app/**/*.js')
          reviewdog_flags: -diff="git diff origin/${{ github.event.repository.default_branch }} app/**/*.js"
          fail_on_error: true
      - name: Filter changed scss
        id: filter-changed-scss
        if: success() || failure()
        run: |
          files=$(git diff --name-only --diff-filter=ACMR origin/${{ github.event.repository.default_branch }} -- 'app/**/*.scss')
          echo "files=${files}" >> $GITHUB_OUTPUT
      - uses: reviewdog/action-stylelint@v1
        if: (success() || failure()) && steps.filter-changed-scss.outputs.files != ''
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          stylelint_input: $(git diff --name-only --diff-filter=ACMR origin/${{ github.event.repository.default_branch }} -- 'app/**/*.scss')
          fail_on_error: true
