name: Test

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUNDLE_ENTERPRISE__CONTRIBSYS__COM: ${{ secrets.BUNDLE_ENTERPRISE__CONTRIBSYS__COM }}
  DB_PASSWORD: yourStrong(!)Password
  SWAGGER_UI_VERSION: v4.15.5
  TZ: Asia/Tokyo
  CI_NODE_TOTAL: 2
  CI_NODE_CPU_CORES: 2
  RAILS_ENV: test

jobs:
  setup-matrix:
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set matrix
        id: set-matrix
        run: |
           seq -s ',' 0 $(($CI_NODE_TOTAL - 1)) | \
             jq -R 'split(",") | map(select(length > 0)) | map(tonumber)' | \
             jq -r '"matrix={\"ci_node_index\":\(.)}"' >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-20.04
    needs:
      - setup-matrix
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: ${{ env.DB_PASSWORD }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.CI_USER_GITHUB_TOKEN }}
      - name: Setup rails application
        uses: ./.github/actions/setup-rails-application
      - name: Bundle assets
        run: |
          NODE_OPTIONS="--max-old-space-size=512" ./node_modules/.bin/webpack
      - name: Update mecabrc
        run: |
          sudo chown runner:runner /etc/mecabrc
          # bundle exec rake mecab:update_mecabrc
      - name: Download spec/examples.txt
        uses: actions/download-artifact@v4
        with:
          pattern: examples-${{ matrix.ci_node_index }}
          path: tmp
      - name: Check if only failed tests should be re-run
        id: failed-tests-only
        run: |
          if [ -e tmp/examples-${{ matrix.ci_node_index }}/examples.txt ]; then
            mv tmp/examples-${{ matrix.ci_node_index }}/examples.txt spec/examples.txt
            sudo chown runner:runner spec/examples.txt
            echo "value=true" >> $GITHUB_OUTPUT
          else
            echo "value=false" >> $GITHUB_OUTPUT
          fi
      - name: Download JUnit XML reports
        if: ${{ steps.failed-tests-only.outputs.value == 'false' }}
        uses: dawidd6/action-download-artifact@v5
        with:
          name: junit-xml-reports-*
          name_is_regexp: true
          path: tmp/junit-xml-reports-downloaded
          branch: ${{ github.event.repository.default_branch }}
          workflow_conclusion: success
        continue-on-error: true
      - name: Split tests by timings
        if: ${{ steps.failed-tests-only.outputs.value == 'false' }}
        uses: r7kamura/split-tests-by-timings@v0
        id: split-tests
        with:
          reports: tmp/junit-xml-reports-downloaded
          glob: spec/**/*_spec.rb
          index: ${{ matrix.ci_node_index }}
          total: ${{ env.CI_NODE_TOTAL }}
      - name: Setup DB
        run: bundle exec rails "parallel:setup[${CI_NODE_CPU_CORES}]"
      - name: Run rspec in parallel
        if: ${{ steps.failed-tests-only.outputs.value == 'false' }}
        run: bundle exec parallel_rspec -n $CI_NODE_CPU_CORES ${{ steps.split-tests.outputs.paths }}
      - name: Re-run rspec only failures
        if: ${{ steps.failed-tests-only.outputs.value == 'true' }}
        run: bundle exec rspec --only-failures --failure-exit-code=0
      - name: Upload JUnit XML reports
        if: ${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref && steps.failed-tests-only.outputs.value == 'false' }}
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: junit-xml-reports-${{ matrix.ci_node_index }}
          path: test_results
      - name: Upload coverage/.resultset.json
        if: ${{ steps.failed-tests-only.outputs.value == 'false' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.ci_node_index }}
          path: coverage/.resultset.json
      - name: Run rspec only failures
        run: bundle exec rspec --only-failures
      - name: Upload spec/examples.txt
        if: (success() || failure()) && hashFiles('spec/examples.txt') != ''
        uses: actions/upload-artifact@v4
        with:
          name: examples-${{ matrix.ci_node_index }}
          path: spec/examples.txt

  report-coverage:
    needs: test
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      pull-requests: write
    if: success() || failure()
    steps:
      - name: Download all coverage artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
      - name: Move generated files
        run: |
          mkdir -p /tmp/coverage
          artifacts=($(ls))
          for artifact in "${artifacts[@]}"; do
            mv ${artifact}/.resultset.json /tmp/coverage/.resultset-${artifact}.json
            rm -r "${artifact}"
          done
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup rails application
        uses: ./.github/actions/setup-rails-application
      - name: Collates all result sets
        run: bundle exec rails "coverage:report[/tmp/coverage/.resultset-*.json]"
      - name: Coverage Report by octocov
        uses: k1LoW/octocov-action@v1
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

  build-github-pages:
    needs: report-coverage
    runs-on: ubuntu-20.04
    if: format('refs/heads/{0}', github.event.repository.default_branch) == github.ref
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
      - name: Checkout swagger-ui
        uses: actions/checkout@v4
        with:
          repository: swagger-api/swagger-ui
          ref: ${{ env.SWAGGER_UI_VERSION }}
          path: swagger-ui
      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: coverage
      - name: Build GitHub Pages
        run: |
          mkdir -p github_pages_artifact/swagger-ui/
          cp swagger-ui/dist/* github_pages_artifact/swagger-ui/
          cp -f main/docs/dist/swagger-ui/* github_pages_artifact/swagger-ui/
          cp -r coverage github_pages_artifact/
      - name: Upload page artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: github_pages_artifact/

  deploy-github-pages:
    needs: build-github-pages
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-20.04
    if: format('refs/heads/{0}', github.event.repository.default_branch) == github.ref
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
