name: Redis container example
on: push

env:
  RUBY_VERSION: 3.1.2
  FREETDS_VERSION: 1.3.17
  DB_HOST: mssql
  DB_USER: sa
  DB_PASSWORD: "yourStrong(!)Password"

jobs:
  build:
    runs-on: ubuntu-22.04
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: ${{ env.DB_PASSWORD }}
    strategy:
      matrix:
        ci_node_total:
          #- 16
          - 2
        ci_node_index:
          - 0,1
          #- 2,3
          #- 4,5
          #- 6,7
          #- 8,9
          #- 10,11
          #- 12,13
          #- 14,15
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Cache freetds
        id: cache-Primes
        uses: actions/cache@v4
        with:
          path: ~/freetds-${{ env.FREETDS_VERSION }}
          key: ${{ runner.os }}-freetds
      - name: Install freetds
        run: |
          cd ~/
          if [ ! -d "freetds-${FREETDS_VERSION}" ]; then
            sudo apt-get update --allow-releaseinfo-change
            sudo apt-get -y install libsasl2-dev
            wget http://www.freetds.org/files/stable/freetds-${FREETDS_VERSION}.tar.gz
            tar -xzf freetds-${FREETDS_VERSION}.tar.gz
            cd freetds-${FREETDS_VERSION}
            sudo ./configure --with-tdsver=7.4
            sudo make
            cd ..
          fi
          cd freetds-${FREETDS_VERSION}
          sudo make install
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: bundle exec rubocop
        run: bundle exec rubocop
      - name: Rspec
        env:
          PARALLEL_TESTS_CONCURRENCY: ${{ matrix.ci_node_total }}
          CONCURRENCY_INDEX: ${{ matrix.ci_node_index }}
        run: |
          yarn install --check-files
          sudo apt-get update && sudo apt-get install netcat
          nc -w 1 -v 127.0.0.1 1433 || true
          nc -w 1 -v 0.0.0.0 1433 || true
          nc -w 1 -v localhost 1433 || true
          tsql -C
          #TDSVER=7.0 tsql -H 127.0.0.1 -p 1433 -U sa -P $DB_PASSWORD
          bundle exec rails "parallel:setup[2]"
          #bundle exec parallel_rspec -n $PARALLEL_TESTS_CONCURRENCY --only-group $CONCURRENCY_INDEX
