name: Validate swagger

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-swagger-files:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Validate swagger.yml
        run: docker run --rm -v $(pwd):/project -w /project usabillabv/openapi3-validator swagger/swagger.yml
