name: Validate swagger

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  validate-swagger-files:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Validate swagger.yml
        run: docker run --rm -v $(pwd):/project -w /project usabillabv/openapi3-validator swagger/swagger.yml
