name: Validate swagger

on:
# push

jobs:
  validate-swagger-files:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0
      - name: Validate swagger.yml
        run: docker run --rm -v $(pwd):/project -w /project usabillabv/openapi3-validator swagger/swagger.yml
